name: CI & CD
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject Environment variables
        run: |
          cat > .env <<EOF
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename package name
        run: mv target/*.jar app.jar

      - name: Pick target
        run: |
          mkdir ./build
          mv ./app.jar ./build

      - name: Transport target
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./build
          remote: /tmp/back_data
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_KEY }}

      - name: Run target
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_KEY }}
          command: |
            cd /tmp/back_data
            cat > .env <<EOF
            ${{ secrets.ENV_FILE }}
            EOF
            nohup java -jar app.jar --server.port=9123 >> /tmp/app.log 2>&1 &